services:
  database:
    image: postgres:15-alpine
    container_name: crewbase
    environment:
      POSTGRES_USER: opgadmin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crew
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  
  # api:
  #   build:
  #     context: .
  #     target: builder
  #   container_name: fastapi-application
  #   environment:
  #     PORT: 8000
  #   ports:
  #     - '8000:8000'
  #   restart: "no"


volumes:
  db: