services:
  db:
    image: postgres:16
    container_name: pgr
    environment:
      POSTGRES_DB: crew
      POSTGRES_USER: opgadmin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opgadmin -d crew"]
      interval: 5s
      timeout: 5s
      retries: 15
  
  api:
    build: .
    container_name: apii
    ports:
      - "6060:6060"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://opgadmin:secret@db:5432/crew

volumes:
  postgres_data: