services:
  database:
    image: postgres:15-alpine
    container_name: crewbase
    restart: always
    environment:
      POSTGRES_USER: opgadmin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crew
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db: