services:
  db:
    image: postgres:16
    container_name: pgr
    environment:
      POSTGRES_DB: crew
      POSTGRES_USER: opgadmin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: apii
    build: .
    depends_on:
      - db
    ports:
      - "6060:6060"

volumes:
  pgdata:
